import mongoose from "mongoose";
import dotenv from "dotenv"

dotenv.config()

const user = new mongoose.Schema({
    twoStep:{
        type:Boolean,
        default:0
    },
    profile:{
        experience:{
            type:String
        },
        full_name:{
            type:String,
            required:true
        },
        username:{
            type:String,
            required:true,
            unique:true
        },
        account_type:{
            type:String,
            required:true
        },
        image:{
            type:String,
            default:"/job/default/avatar.png"
        },
        pdf:{
            type:String
        },
        audio:{
            type:String
        },
        email:{
            type:String,
            required:true,
            unique:true
        },
        password:{
            type:String,
            required:true
        },
        connections:{
            count:{
                type:Number,
                default:0
            },
            ids:{
                type:Array,
                default:[]
            },
            my_connections:{
                type:Array,
                default:[]
            }
        },
        country:{
            type:String,
            required:true
        },
        is_verified:{
            type:Boolean,
            default:false
        },
        hoursPerWeek:{
            type:String,
            default:"More than 30 hrs/week"
        },
        language:{
            type:Array,
            default:[]
        },
        education:{
            type:Array,
            default:[]
        },
        title:{
            type:String,
            default:"Data Entry"
        },
        description:{
            type:String,
            default:"I am a data entry freelancer."
        },
        work_history:{
            type:Array,
            default:[]
        },
        skills:{
            type:Array,
            default:[]
        },
        my_projects:{
            type:Array,
            default:[]
        },
        certificates:{
            type:Array,
            default:[]
        },
        employment_history:{
            type:Array,
            default:[]
        },
        per_hour:{
            type:Number,
            default:1,
        },
        signup_method:{
            type:String,
            default:null
        },
        available:{
            type:Boolean,
            default:1
        },
        rating:{
            type:Number,
            default:0
        }
    },
    saved_jobs:{
        type:Array,
        default:[]
    },
    rejected_jobs:{
        type:Array,
        default:[]
    },
    dislike:{
        type:Array,
        default:[]
    },
    spent:{
        type:Number,
        default:0
    },
    balance:{
        type:Number,
        default:0
    },
    transactions:[{
        to:{
            type:String
        },
        amount:{
            type:Number
        },
        currency:{
            type:String
        },
        pay_id:{
            type:String
        },
        time:{
            type:Date
        },
        status:{
            type:String
        }
    }],
    withdrawal_methods:{
        type:Object,
        default:null
    },
    my_proposals:{
        type:Array,
        default:[]
    },
    notifications:{
        type:Object
    },
    banned:{
        type:Boolean,
        default:0
    },
    project_cost:[
        {
            amount:{
                type:Number
            }
        },{
            month:{
                type:String
            }
        }
    ],
    cooldown:{
        type:Number,
        default:new Date()
    }
})

export const userSchema = mongoose.model("users",user)